# -*- coding: utf-8 -*-
"""TRIZER PYTHON ASSIGNMENT 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XimOde8l61B8gXZ-UnB9tGJkl0CvXQ_Z
"""



#creating a list of dictionaries
students_info1=[{"name":"Stacy","age":28,"height":30.6,"hobbies":["swimming","singing","playing football"]},
               {"name":"Joy","age":27,"height":40.7,"hobbies":["reading","playing hockey","reading"]}]
print(students_info1)

#adding new list of dictionary
students_info1.append({"name":"Sharly","age":37,"height":40.5,"hobbies":["hicking","cooking","reading novels"]})
students_info1.append({"name":"Sarah","age":23,"height":27.7,"hobbies":["sleeping","listening to music","playing footbal"]})
students_info1.append({"name":"Benard","age":27,"height":30.7,"hobbies":["laughing","cooking","reading"]})
print(students_info1)

#updating
students_info={"name":"Stacy","age":28,"height":30.6,"hobbies":["swimming","singing","playing football"]}
students_info.update({"height":34.6})
print(students_info)

#QZ.2
#Another list of dictionaries
students_info2=[{"name":"Jane","age":35,"height":37.2,"hobbies":["travelling","playing football","listening to music"]},
               {"name":"Rose","age":26,"height":52.4,"hobbies":["socializing","reading novels"]}]
print(students_info2)

#merging list
students_info3=students_info1+students_info2
print(students_info3)

#couning the number  of students in a list of dictionaries
count=0
for student in students_info3:
    count+=1
print(count)

#calculating the sum of students ages
total_age=0
for student in students_info3:
    total_age+=student["age"]
print(total_age)

#calculating the average age of the students
average_age=total_age/count
print(average_age)

#identifying students with specific hobby
for student in students_info3:
    if "singing" in student["hobbies"]:
        print(student["name"])

#finding the tallest student
tallest_student=students_info3[0]
for student in students_info3:
    if student["height"]>tallest_student["height"]:
        tallest_student=student
print(tallest_student["name"])

